name: RpgU
version: '${project.version}'
main: me.udnek.rpgu.RpgU
api-version: '1.21.4'
depend: [ItemsCoreU, JeiU]
commands:
  debug_equipment:
    description: "debug_equipment"
    usage: "/debug_equipment"
    aliases: []
    permission: rpgu.admin
    permission-message: "You do not have permission to use this command"
  custom_damage_system:
    description: "custom_damage_system"
    usage: "/custom_damage_system"
    aliases: []
    permission: rpgu.admin
    permission-message: "You do not have permission to use this command"
  reset_cooldown:
    description: "reset_cooldown"
    usage: "/reset_cooldown"
    aliases: [ ]
    permission: rpgu.admin
    permission-message: "You do not have permission to use this command"
  set_food:
    description: "set_food"
    usage: "/set_food"
    aliases: [ ]
    permission: rpgu.admin
    permission-message: "You do not have permission to use this command"